# Generated by Django 6.0.2 on 2026-03-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slung',
            new_name='slug',
        ),
    ]
