# Generated by Django 6.0.2 on 2026-03-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
